export const Users = [
  {
    id: 1,
    profilePicture: "/assets/person/Alia.jpeg",
    username: "Alia Bhatt",
  },
  {
    id: 2,
    profilePicture: "/assets/person/Kapil.jpeg",
    username: "Kapil Sharma",
  },
  {
    id: 3,
    profilePicture: "/assets/person/Kartik.jpeg",
    username: "Kartik Aryan",
  },
  {
    id: 4,
    profilePicture: "/assets/person/Katrina.jpeg",
    username: "Katrina kaif",
  },
  {
    id: 5,
    profilePicture: "/assets/person/Salaman.jpeg",
    username: "Salaman Khan",
  },
  {
    id: 6,
    profilePicture: "/assets/person/Shahid.jpeg",
    username: "Shahid Kapoor",
  },
  {
    id: 7,
    profilePicture: "/assets/person/Shahrukh.jpeg",
    username: "Shahrukh Khan",
  },
  {
    id: 8,
    profilePicture: "/assets/person/Sonakshi.jpeg",
    username: "Sonakshi Sinha",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "/assets/posts/post1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "/assets/posts/post2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "/assets/posts/post3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "/assets/posts/post4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "/assets/posts/post5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "/assets/posts/post6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "/assets/posts/post7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "/assets/posts/post8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    photo: "/assets/posts/post9.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 10,
    photo: "/assets/posts/post10.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 11,
    photo: "/assets/posts/post11.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 12,
    photo: "/assets/posts/post12.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 13,
    photo: "/assets/posts/post13.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 14,
    photo: "/assets/posts/post14.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 15,
    photo: "/assets/posts/post15.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
];
